### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mwinkl** [S120/benchmark#5] opened 2020-01-09 10:36 UTC
hello,
it would be great if someone could help or has an advice:
I try to run the benchmark model  with Spring Tool Suit 4 on Linux.

![exceptionmain](https://user-images.githubusercontent.com/59689021/72060378-2301d680-32d4-11ea-9893-be67c562d70f.png)

![NullPointerException](https://user-images.githubusercontent.com/59689021/72060383-25643080-32d4-11ea-85a6-e0c6fb1736d6.png)

**Comment by alessandrocaiani** [comment] 2020-01-09 12:14
Hi,
I am a little bit confused because the error in the first screenshoot seems to be solved in the second one, otherwise the simulation would not start. Incidentally the problem in the first screenshot should be caused by the fact that there is a "jabm" folder in excess on github repository that cause jabm not been recognized as a "project" by eclipse. Remove the folder in excess and correctly import the project should solve the problem, but I guess you already discovered this by your own from what I see in the second screenshot.
The second problem is related to the fact that the prng definition was changed after uploading the code of the benchamerk on github and apparently only the modelBenchmark_light.xml file was updated accordingly. It's a minor change:
a) the prng bean definition should be replaced with this one:
<bean id="prng" class="net.sourceforge.jabm.prng.MersenneTwister">
<property name="seed" value="1"/>
</bean>
b) the following property should be added to the consumptionFirmPrototype, capitalFirmPrototype, and governmentPrototype beans.
<property name="prng" ref="prng"/>

For your convenience, here attached is the amended .xml
I checked it and it works.
Best, and thanks for your interest in our research.
Alessandro


________________________________
Da: mwinkl <notifications@github.com>
Inviato: giovedì 9 gennaio 2020 11:36
A: S120/benchmark <benchmark@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: [S120/benchmark] Error (#5)


hello,
it would be great if someone could help or has an advice:
I try to run the benchmark model with Spring Tool Suit 4 on Linux.

[exceptionmain]<https://user-images.githubusercontent.com/59689021/72060378-2301d680-32d4-11ea-9893-be67c562d70f.png>

[NullPointerException]<https://user-images.githubusercontent.com/59689021/72060383-25643080-32d4-11ea-85a6-e0c6fb1736d6.png>

**Comment by mwinkl** [comment] 2020-01-10 13:37
Thank you for your answer.

Sorry for the confusion, the first screenshot refers to a simulation attempt of the “modelBenchmark_full.xml”, the second screenshot of “mainBenchmark_full.xml”.

I followed your advice to my best knowledge (I removed both the “benchmark” and “jabm” und imported them again. Now the resource properties of “benchmark” and “jabm” are both of Type "Project").

Now, the simulation attempt of “modelBenchmark_full” shows:
![modelBenchmark_full_error](https://user-images.githubusercontent.com/59689021/72156554-1fdf1700-33b6-11ea-8ba1-1e07ba62469f.png)



And the simulation attempt of “mainBenchmark_full” shows:
![mainBenchmark_full_NullPointerException](https://user-images.githubusercontent.com/59689021/72156560-253c6180-33b6-11ea-8b38-5c2a039617c2.png)

Thank you for your help in advance.
m

**Comment by alessandrocaiani** [comment] 2020-01-10 14:12
You should run a configuartion using the Main xml as in your second example: the main then imports the other two xml configuration files required to run the simulation (modelBenchmark and reports).
 It seems there is another little misspecification in the modelBenchmark_full.xml which very likely related again to the change of the prng I mentioned before: as far as I see from your screenshot the simulation was running fine till period 101. Then the bank bakruptcy strategy asks to sample from a Uniform whose bean is probably misspecified in the modelBenchmark_full.xml. Try to look at the modelBenchmark_light.xml to see how the Uniform of the BankBankruptcyBailoutCAR should be correctly specified and amend the configuration file. Unfortunately I am now hospitalized for a surgery and cannot check it by myself. I apologize for this inconvenience. There might be a couple of other similar mistakes actually because, as I wrote in my previous email, it seems we did not update the full model configuration file after the change in the prng. If you just want to see how the code works may I suggest to overcome the issue by running the light version instead of the full one until I'll have amended the full configuration file? It only changes the number of agents (fewer)(not their behaviors) and it is faster.
Best and my apologies again
Ale

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________
Da: mwinkl <notifications@github.com>
Inviato: venerdì 10 gennaio 2020, 14:37
A: S120/benchmark
Cc: alessandrocaiani; Comment
Oggetto: Re: [S120/benchmark] Error (#5)


Thank you for your answer.

Sorry for the confusion, the first screenshot refers to a simulation attempt of the “modelBenchmark_full.xml”, the second screenshot of “mainBenchmark_full.xml”.

I followed your advice to my best knowledge (I removed both the “benchmark” and “jabm” und imported them again. Now the resource properties of “benchmark” and “jabm” are both of Type "Project").

Now, the simulation attempt of “modelBenchmark_full” shows:
[modelBenchmark_full_error]<https://user-images.githubusercontent.com/59689021/72156554-1fdf1700-33b6-11ea-8ba1-1e07ba62469f.png>

And the simulation attempt of “mainBenchmark_full” shows:
[mainBenchmark_full_NullPointerException]<https://user-images.githubusercontent.com/59689021/72156560-253c6180-33b6-11ea-8b38-5c2a039617c2.png>

Thank you for your help in advance.
m

**Comment by alessandrocaiani** [comment] 2020-01-13 15:54
Dear M.,
I have updated the full model configuration file and uploaded it on GitHub. As I supposed, there was a reference to the prng missing in the properties of the bankBankrupcty strategy, so the Uniform distribution employed by that strategy could not access the prng.
Now it should (and seems to)  work fine.
Best


________________________________
Da: Alessandro Caiani <alessandro.caiani@hotmail.it>
Inviato: venerdì 10 gennaio 2020 15:12
A: S120/benchmark <reply@reply.github.com>
Oggetto: Re: [S120/benchmark] Error (#5)

You should run a configuartion using the Main xml as in your second example: the main then imports the other two xml configuration files required to run the simulation (modelBenchmark and reports).
 It seems there is another little misspecification in the modelBenchmark_full.xml which very likely related again to the change of the prng I mentioned before: as far as I see from your screenshot the simulation was running fine till period 101. Then the bank bakruptcy strategy asks to sample from a Uniform whose bean is probably misspecified in the modelBenchmark_full.xml. Try to look at the modelBenchmark_light.xml to see how the Uniform of the BankBankruptcyBailoutCAR should be correctly specified and amend the configuration file. Unfortunately I am now hospitalized for a surgery and cannot check it by myself. I apologize for this inconvenience. There might be a couple of other similar mistakes actually because, as I wrote in my previous email, it seems we did not update the full model configuration file after the change in the prng. If you just want to see how the code works may I suggest to overcome the issue by running the light version instead of the full one until I'll have amended the full configuration file? It only changes the number of agents (fewer)(not their behaviors) and it is faster.
Best and my apologies again
Ale

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________
Da: mwinkl <notifications@github.com>
Inviato: venerdì 10 gennaio 2020, 14:37
A: S120/benchmark
Cc: alessandrocaiani; Comment
Oggetto: Re: [S120/benchmark] Error (#5)


Thank you for your answer.

Sorry for the confusion, the first screenshot refers to a simulation attempt of the “modelBenchmark_full.xml”, the second screenshot of “mainBenchmark_full.xml”.

I followed your advice to my best knowledge (I removed both the “benchmark” and “jabm” und imported them again. Now the resource properties of “benchmark” and “jabm” are both of Type "Project").

Now, the simulation attempt of “modelBenchmark_full” shows:
[modelBenchmark_full_error]<https://user-images.githubusercontent.com/59689021/72156554-1fdf1700-33b6-11ea-8ba1-1e07ba62469f.png>

And the simulation attempt of “mainBenchmark_full” shows:
[mainBenchmark_full_NullPointerException]<https://user-images.githubusercontent.com/59689021/72156560-253c6180-33b6-11ea-8b38-5c2a039617c2.png>

Thank you for your help in advance.
m

**Comment by mwinkl** [comment] 2020-01-17 12:26
Thank you for your effort.
Since I can not tell if Iam doing something wrong or if its an "error", I have another exception during the "mainBenchmark_full.xml" simulation:

![BufferOverflow](https://user-images.githubusercontent.com/59689021/72612332-bd919380-392c-11ea-9b98-954f1be1e458.png)

The working memory is set to 4GB. And the heap size was not at maximum (217M of 259M) when the simulation was aborted.

Thank you again.

**Comment by antoinegodin** [comment] 2020-01-21 08:07
Hi,

I think that the issue was related to the serialization tick which saves the bites of the entire population and can get quite heavy on the memory. Furthermore, we never quite developed the entire process so I believe it is better not to use it. I pushed the changes on the xml a minute ago and this should work now.

**Comment by mwinkl** [comment] 2020-01-23 11:19
Hello, 
and again, thank you for your help. 
When I try to run the “modelBenchmark_full”, the same error keeps reappearing:

![simulationController](https://user-images.githubusercontent.com/59689021/72980230-7565eb80-3dda-11ea-80ba-a2e271d01e83.png)

I made sure that the jabm folder is the right one (I used smart import to verify that the imported folder is actually an Eclipse project) and the “mainBenchmark_full” simulation was running before I tried to start “modelBenchmark_full” (for configuration).

**Comment by antoinegodin** [comment] 2020-01-24 09:03
Hi,

You should not call the modelBenchmark file but the mainBenchmark one. The main file will call the model file. We have split the entire configuration file between three files: main, model and report for ease of reading but the entry point is always the main one. If you read that file, you will see that it refers to the other two files:

import resource="modelBenchmark_full.xml"
import resource="reports.xml"

So if you revert the call to mainBenchamrk file (either the full or the light version) this should work.

Best,

Antoine.

**Comment by mwinkl** [comment] 2020-01-24 09:23
Thank you very much, this clarifies alot. The full and light version are both working now.

**Comment by antoinegodin** [comment] 2020-01-24 09:47
Thank you for your response, I'm closing the issue now.

**Closed as completed by antoinegodin** 2020-01-24 09:47 UTC
